---
title: "Data Visualization"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    toc_collapsed: TRUE
    toc_depth: 3
    number_sections: TRUE
    theme: lumen
---

# Welcome!

This is meant to be a non-exhaustive collection of information from a variety of different sources to help refine visualizations.

All code in this compilation uses [ggformula](https://www.mosaic-web.org/ggformula/reference/index.html).


## Introduction to Visualization Resources


This compilation assumes a basic understanding of creating the initial graph - and will therefore focus on ways to refine a graph further. As such, a few other resources for those wanting more introduction to graphing are included below.

-   **Data Viz Basics:** Claus O. Wilke has a great resource discussing many [Fundamentals of Data Visualization](https://clauswilke.com/dataviz/) made freely available.

-   **R Graph Ideas & Codes:** The [R Graph Gallery](https://r-graph-gallery.com/index.html) gives many examples (and code) of graphs available.

- **ggformula intro:** The following [article](https://www.mosaic-web.org/ggformula/articles/pkgdown/ggformula-long.html) discusses many different types of plots and how to use ggformula to create them.


## Helpful Packages

This compilation utilizes many packages - but here are a few key ones to start:

-   mosaic (also using the ggformula way of graphing)
-   forcats (ordering factors by a statistic)
-   gridextra (arranging multiple graphs together)
-   tidyverse (wrap text in labels using str_wrap)
-   scales (adjusting numeric scales and wrap labels)
-   ggforce (abbreviating labels)
-   tidyr (wrangle data)
-   ggrepel (avoid overlapping labels)
-   readr (reading in dataset and parse numbers)
-   stringr (adjusting strings)

Specific Plots

-   ggridges (ridge plots)
-   ggmosaic (creating mosaic plots)
-   maps (creating maps)

The following packages are mostly used for the variety of datasets they offer.  

-   Lock5Data 
-   socviz
-   palmerpenguins
-   socviz 
-   MASS
-   gapminder

Color Packages

-   RColorBrewer
-   viridis 
-   paletteer
-   colorspace


## Additional Refinement Resources


Throughout the website I link to many resources - but most commonly, I will reference the ggplot2 book listed below.

-   **Refinements using ggplot2:** The [ggplot2](https://ggplot2-book.org/mastery.html) book is a wealth of information not only on creating graphs but also refining them.

-   **ggplot2 Cheat Sheet:** [Two pages](https://rstudio.github.io/cheatsheets/data-visualization.pdf) packed of information on creating & refining graphs using ggplot2
